language: ruby
rvm:
  - 2.2.6
  - 2.3.3
env:
  - TARGET=redmine REDMINE_VERSION=3.2.6
  - TARGET=plugin REDMINE_VERSION=3.2.6
before_install: sh travis/before_install.sh
script: sh travis/exec_test.sh
